### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#101]
Trolig ved sletting av filer (Dette skjer automatisk før ny daisy202 blir produsert). Denne er fra kl. 03, nytt lydutdrag ble produsert kl. 05. Ser ut som on_book_modified blir kalt i stedet for on_book_deleted

Endret lydbok i mappa: 624347180514

An error occured while handling the book

Traceback (most recent call last): File "/opt/produksjonssystem/produksjonssystem/core/pipeline.py", line 722, in _handle_book_events_thread self.on_book_modified() File "/opt/produksjonssystem/produksjonssystem/make_abstracts.py", line 39, in on_book_modified self.on_book() File "/opt/produksjonssystem/produksjonssystem/make_abstracts.py", line 50, in on_book self.utils.filesystem.copy(self.book["source"], temp_absdir) File "/opt/produksjonssystem/produksjonssystem/core/utils/filesystem.py", line 170, in copy assert os.path.isdir(source) or os.path.isfile(source), "Filesystem.copy(): source must be either a file or a directory: " + str(source) AssertionError: Filesystem.copy(): source must be either a file or a directory: /media/share/daisy202/624347180514

**Comment by espso** [comment]
@josteinaj Greier kun å reprodusere hvis jeg toucher og så sletter rett etterpå. Er det ok hvis jeg legger in en if?
if(os.path.isdir(self.book["source"])):

**Comment by josteinaj** [comment]
Hmm, ja, men det er litt rart hele greia. Skulle gjerne visst hvorfor det skjer. Vil du fortsatt sende feilmelding, bare en litt finere feilmelding?

**Comment by josteinaj** [comment]
Skjer dette fortsatt?

**Comment by espso** [comment]
Ser det har skjedd noen ganger med 611823, altså aftenposten. Ikke noen andre. Gårsdagens, altså ikke den som blir slettet/ er slettet.

**Comment by josteinaj** [comment]
Ok, da så. Tenkte kanskje det hadde blitt fikset tidligere.

**Comment by espso** [comment]
Skjer fortsatt innmellom når aviser blir slettet. Kanskje hvis slettinga tar litt tid eller noe sånt

**Comment by josteinaj** [comment]
@espso løste dette seg i edd3594386786eff1983ba38eb07e2f70acf12e8?

**Comment by espso** [comment]
Ser ikke ut som det skjer lenger.
