### ISSUE TITLE
Pene stacktraces

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#102]
Istedenfor dette:

---

<code>
Traceback (most recent call last): File "/opt/produksjonssystem/produksjonssystem/core/utils/filesystem.py", line 296, in run_static completedProcess = subprocess.run(args, stdout=stdout, stderr=stderr, shell=shell, cwd=cwd, timeout=timeout, check=check) File "/usr/lib/python3.5/subprocess.py", line 708, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['/opt/daisy-pipeline2/cli/dp2', 'nlb:html-to-pef', '--braille-standard', '(dots:6)(grade:0)', '--html', '/tmp/tmpnffruc5q/119278.html', '--line-spacing', 'double', '--duplex', 'false', '--background']' returned non-zero exit status 255
</code>

---

Så hadde det vært fint med noe som dette:

```
Traceback (most recent call last):
  File "/opt/produksjonssystem/produksjonssystem/core/utils/filesystem.py", line 296, in run_static
    completedProcess = subprocess.run(args, stdout=stdout, stderr=stderr, shell=shell, cwd=cwd, timeout=timeout, check=check)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/daisy-pipeline2/cli/dp2', 'nlb:html-to-pef', '--braille-standard', '(dots:6)(grade:0)', '--html', '/tmp/tmpnffruc5q/119278.html', '--line-spacing', 'double', '--duplex', 'false', '--background']' returned non-zero exit status 255
```

Kanskje det kunne vært en ny funksjon i report.py som gjorde dette, også kan vi bytte ut de stedene hvor vi logger stacktrace med et kall til den funksjonen:

Så istedenfor:

```python
report.debug(traceback.format_exc())
```

Så kan vi istedenfor gjøre:

```
report.exception(traceback)
# ... eller ...
report.exception(traceback, "En feil oppstod ved bla bla bla.")
```

**Comment by espso** [comment]
Bør vi ha med en parameter for hva slags status det er? Først tenkte jeg alt til error eller info, men det kan jo være noen ganger debug er bedre, hvis det er feil vi ikke vil ha i mail.

self.utils.report.exception(info, traceback.format_exc())

**Comment by josteinaj** [comment]
Ja, god poeng. Hva med å legge til et "preformatted"-argument til alle logge-funksjonene?

```python
report.info(message, preformatted=False)
report.error(message, preformatted=False)
...
```

**Comment by espso** [comment]
Ja det funker

**Comment by josteinaj** [comment]
Ser bra ut!

![skjermbilde fra 2018-06-07 13-32-37](https://user-images.githubusercontent.com/295481/41097161-53b008c0-6a57-11e8-95d6-f945d70f32a1.png)

**Comment by espso** [comment]
Fint
