### ISSUE TITLE
Systemet henger

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#105]
Den kjører "Nordisk EPUB til NLBPUB" og "NLBPUB til PEF" men blir aldri ferdig. Pipeline 2 sier det bare er "NLBPUB til PEF" som kjører, og det er flere andre jobber som er "IDLE". Trolig noe med Pipeline 2.

**Comment by josteinaj** [comment]
Slettet alle andre jobber enn "NLBPUB til PEF"-jobben fra Pipeline 2. De andre pipeline'ene står fortsatt og kjører i produksjonssystemet. Kanskje de andre pipeline'ene blir blokkert av "NLBPUB til PEF"-jobben.

**Comment by josteinaj** [comment]
Det hjalp ikke å slette "NLBPUB til PEF"-jobben fra Pipeline 2. Den andre jobben i Pipeline 2 som var lagt til (nyhetsbrev) startet ikke av seg selv. Jeg tror dette er en feil med Pipeline 2, enten i selve motoren eller i PEF-skriptet.

- [ ] sjekk om det er mulig å kjøre flere jobber parallelt i Pipeline 2 (det skal det egentlig være)
- [ ] finn en måte å detektere at Pipeline 2 har stoppet opp
  - kanskje hvis en jobb ligger i flere minutter som "IDLE" selv om det ikke er 4 jobber som kjører
  - eller rett og slett hvis en jobb tar mer enn en time; gjør en omstart av Pipeline 2

Når en DP2-jobb er slettet kommer denne feilen:
```
2018-06-05 16:13:44,923 ERROR    [book in nlbpub-to-pef         ] Traceback (most recent call last):
  File "/opt/produksjonssystem/produksjonssystem/core/utils/filesystem.py", line 292, in run_static
    completedProcess = subprocess.run(args, stdout=stdout, stderr=stderr, shell=shell, cwd=cwd, timeout=timeout, check=check)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/daisy-pipeline2/cli/dp2', 'status', 'ef34d572-8419-4516-baa5-bc9451c2b94c']' returned non-zero exit status 255
```
Denne kan oppstå sporadisk ellers også, derfor bør den nok ikke umiddelbart stoppe hele jobben. Men kanskje hvis denne feilmeldingen kommer kontinuerlig i 2-3 minutter så kan vi anta at det har skjedd noe feil i systemet og ta en omstart av DP2?

**Comment by josteinaj** [comment]
Tror a2901b4b472cf67c965b7bb44fab5e9390d64921 fikser dette. Vi får se om det skjer igjen...

**Comment by josteinaj** [comment]
Har ikke hørt om at vi har hatt dette problemet siden sist. Jeg lukker denne.
