### ISSUE TITLE
zip_ref.extractall(directory): EOFError

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#11]
Running several conversions after one another, this happened once:

```
2017-11-16 13:30:08,249 ERROR    [Validering av Nordisk EPUB 3] Traceback (most recent call last):
  File "/home/jostein/nlb/produksjonsystem/produksjonssystem/core/pipeline.py", line 352, in _handle_book_events_thread
    self.on_book_modified()
  File "/home/jostein/nlb/produksjonsystem/produksjonssystem/incoming_nordic.py", line 32, in on_book_modified
    self.on_book()
  File "/home/jostein/nlb/produksjonsystem/produksjonssystem/incoming_nordic.py", line 66, in on_book
    self.utils.epub.unzip(self.book["source"], book_dir)
  File "/home/jostein/nlb/produksjonsystem/produksjonssystem/core/utils/epub.py", line 42, in unzip
    zip_ref.extractall(directory)
  File "/usr/lib/python3.5/zipfile.py", line 1349, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/lib/python3.5/zipfile.py", line 1337, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python3.5/zipfile.py", line 1401, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/lib/python3.5/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib/python3.5/zipfile.py", line 844, in read
    data = self._read1(n)
  File "/usr/lib/python3.5/zipfile.py", line 912, in _read1
    data += self._read2(n - len(data))
  File "/usr/lib/python3.5/zipfile.py", line 947, in _read2
    raise EOFError
EOFError

2017-11-16 13:30:08,249 ERROR    [140279249049344] An error occured while handling the book
Traceback (most recent call last):
  File "/home/jostein/nlb/produksjonsystem/produksjonssystem/core/pipeline.py", line 352, in _handle_book_events_thread
    self.on_book_modified()
  File "/home/jostein/nlb/produksjonsystem/produksjonssystem/incoming_nordic.py", line 32, in on_book_modified
    self.on_book()
  File "/home/jostein/nlb/produksjonsystem/produksjonssystem/incoming_nordic.py", line 66, in on_book
    self.utils.epub.unzip(self.book["source"], book_dir)
  File "/home/jostein/nlb/produksjonsystem/produksjonssystem/core/utils/epub.py", line 42, in unzip
    zip_ref.extractall(directory)
  File "/usr/lib/python3.5/zipfile.py", line 1349, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/lib/python3.5/zipfile.py", line 1337, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python3.5/zipfile.py", line 1401, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/lib/python3.5/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib/python3.5/zipfile.py", line 844, in read
    data = self._read1(n)
  File "/usr/lib/python3.5/zipfile.py", line 912, in _read1
    data += self._read2(n - len(data))
  File "/usr/lib/python3.5/zipfile.py", line 947, in _read2
    raise EOFError
EOFError

```

**Comment by josteinaj** [comment]
(guessing this was due to overwriting a book while it was being unzipped)

**Comment by josteinaj** [comment]
A descriptive error message has been added. This is unlikely to happen in practice. Closing for now.
