### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#133]
```
Traceback (most recent call last):
  File "/opt/produksjonssystem/produksjonssystem/core/pipeline.py", line 811, in _handle_book_events_thread
    book_metadata = Metadata.get_metadata_from_book(self, self.book["source"])
  File "/opt/produksjonssystem/produksjonssystem/core/utils/metadata.py", line 1054, in get_metadata_from_book
    for p in Metadata.metadata_cache:
RuntimeError: dictionary changed size during iteration
```

**Comment by josteinaj** [comment]
Fikset i 1fa7f7ddd25f5c99919e988585ff53f559af0732.
