### ISSUE TITLE
Header values may not contain linefeed or carriage return characters

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#186]
```
2019-02-06 09:25:51,540 ERROR    [book in incoming-nordic       ] An error occured while sending email
Traceback (most recent call last):
  File "/opt/produksjonssystem/produksjonssystem/core/pipeline.py", line 971, in _handle_book_events_thread
    should_message_slack=self.utils.report.should_message_slack)
  File "/opt/produksjonssystem/produksjonssystem/core/utils/report.py", line 373, in email
    msg['Subject'] = subject
  File "/usr/lib/python3.5/email/message.py", line 410, in __setitem__
    self._headers.append(self.policy.header_store_parse(name, val))
  File "/usr/lib/python3.5/email/policy.py", line 138, in header_store_parse
    raise ValueError("Header values may not contain linefeed "
ValueError: Header values may not contain linefeed or carriage return characters
```

**Comment by josteinaj** [comment]
Skal være fikset i 1b8b7d1d3a1fb0acfa6b5004c25f23ea14d829cb.
