### ISSUE TITLE
Error overwriting existing files

### ISSUE THREAD

**Issue by olavindergaard** [nlbdev/produksjonssystem#19]
```
Ny bok i mappa: 561998.epub
Validerer EPUB...
Genererer ACE-rapport...
Boken er valid. Kopierer til EPUB master-arkiv.
Lagrer 561998 i /media/archive/master/EPUB/...
561998 finnes i /media/archive/master/EPUB/ fra før; eksisterende kopi blir slettet
An error occured while handling the book
Traceback (most recent call last):
  File "/opt/produksjonssystem/produksjonssystem/core/pipeline.py", line 369, in _handle_book_events_thread
    self.on_book_created()
  File "/opt/produksjonssystem/produksjonssystem/incoming_nordic.py", line 43, in on_book_created
    self.on_book()
  File "/opt/produksjonssystem/produksjonssystem/incoming_nordic.py", line 96, in on_book
    archived_path = self.utils.filesystem.storeBook(epub.asDir(), epub.identifier())
  File "/opt/produksjonssystem/produksjonssystem/core/utils/filesystem.py", line 170, in storeBook
    shutil.rmtree(target)
  File "/usr/lib/python3.5/shutil.py", line 478, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 476, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/media/archive/master/EPUB/561998'
```

**Comment by josteinaj** [comment]
Kan hende at noen har mappen eller en fil i mappen åpen et sted? Da går det ikke an å overskrive tror jeg.

**Comment by olavindergaard** [comment]
:1st_place_medal: Hehe, det var akkurat det som var problemet. Vi får bare informere om at man holder seg unna mapper man ikke jobber med selv.
