### ISSUE TITLE
Monitoring of input directory sometimes stops working

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#3]

**Comment by josteinaj** [comment]
Probably because of:

```
2017-11-16 12:15:52,620 DEBUG    Deep checking recently changed book: 558696.epub
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jostein/nlb/produksjonsystem/produksjonssystem/core/pipeline.py", line 235, in _monitor_book_events_thread
    self._update_md5(f)
  File "/home/jostein/nlb/produksjonsystem/produksjonssystem/core/pipeline.py", line 211, in _update_md5
    assert os.path.exists(path)
AssertionError
```

- account for the state which causes this assertion error
- surround threads in a try/except, so that threads don't stop working on unexpected errors
- possibly email unexpected errors to an administrator
