### ISSUE TITLE
Shutdown gir feilmelding på server

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#361]
Kan ikke bruke API kallet for shutdown, da det gir en internal server error

**Comment by josteinaj** [comment]
Fra loggfila:

```
2022-06-24 12:02:19,818 ERROR    [Thread-2126                   ] http://0.0.0.0:3875/prodsys/v1/kill5973637670039528/
Traceback (most recent call last):
  File "/home/itadmin/.local/lib/python3.7/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/itadmin/.local/lib/python3.7/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/produksjonssystem/produksjonssystem/core/server.py", line 303, in kill
    raise RuntimeError("Not running with the Werkzeug Server")
RuntimeError: Not running with the Werkzeug Server
2022-06-24 12:02:19,860 INFO     [Thread-2126                   ] 127.0.0.1 - - [24/Jun/2022 12:02:19] "POST /prodsys/v1/kill5973637670039528/ HTTP/1.1" 500 -
2022-06-24 12:02:19,864 INFO     [Thread-2125                   ] 158.39.103.140 - - [24/Jun/2022 12:02:19] "GET /prodsys/v1/shutdown HTTP/1.1" 500 -
2022-06-24 12:02:20,111 INFO     [main thread                   ] Sender stoppsignal til alle pipelines...
```

Fra Slack:
```
Jostein: nlb prodsys shutdown
NLB: Could not query the production system (HTTP: 500 -- http://nlbprod1.nb.no:3875/prodsys/v1/shutdown)
```

Så API-kallet kan nok brukes men gir av en eller annen grunn en feilmelding sånn at det ser ut som at det ikke virker.
