### ISSUE TITLE
Bedre feilmelding når boka ikke finnes

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#73]
```
Traceback (most recent call last): File "/opt/produksjonssystem/produksjonssystem/core/pipeline.py", line 428, in _handle_book_events_thread self.on_book_modified() File "/opt/produksjonssystem/produksjonssystem/insert_metadata.py", line 23, in on_book_modified self.on_book() File "/opt/produksjonssystem/produksjonssystem/insert_metadata.py", line 31, in on_book epub = Epub(self, self.book["source"]) File "/opt/produksjonssystem/produksjonssystem/core/utils/epub.py", line 30, in init assert os.path.exists(book_path), "'{}' must exist".format(book_path) AssertionError: '/media/archive/master/NLBPUB/562544' must exist
```

**Comment by espso** [comment]
For å unngå disse må assert gjøres om fra
```
 assert os.path.exists(book_path), "'{}' must exist".format(book_path) 
```
 til noe sånt
```
if not os.path.exists(book_path):
            self.pipeline.utils.report.error("Epub does not exist anymore." + book_path)
            return False
```
Ser at de som hovedsaklig havner i mailene er fra epub.py og filesystem.py på grunn av sletting.

**Comment by espso** [comment]
Asserten er fjernet for slettede bøker. Får fortsatt stackstrace under for slettede bøker:

Traceback (most recent call last):
  File "/opt/produksjonssystem/produksjonssystem/core/pipeline.py", line 904, in _handle_book_events_thread
    result = self.on_book_modified()
  File "/opt/produksjonssystem/produksjonssystem/insert_metadata.py", line 28, in on_book_modified
    return self.on_book()
  File "/opt/produksjonssystem/produksjonssystem/insert_metadata.py", line 36, in on_book
    epub = Epub(self, self.book["source"])
TypeError: __init__() should return None, not 'bool'

**Comment by josteinaj** [comment]
Se også duplikat: #173
