### ISSUE TITLE
Permission denied: 'dashboard_.png' -> 'dashboard.png'

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#81]
```
Traceback (most recent call last):
  File "/opt/produksjonssystem/produksjonssystem/core/plotter.py", line 165, in run
    self.plot([p[0].uid for p in self.pipelines], "dashboard")
  File "/opt/produksjonssystem/produksjonssystem/core/plotter.py", line 146, in plot
    os.rename(os.path.join(self.report_dir, name + "_.png"), os.path.join(self.report_dir, name + ".png"))
PermissionError: [Errno 13] Permission denied: '/media/archive/rapporter/dashboard_.png' -> '/media/archive/rapporter/dashboard.png'
```

**Comment by josteinaj** [comment]
Har ikke sett denne feilmeldingen på en stund.
