### ISSUE TITLE
local variable 'smildoc_abstract' referenced before assignment

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#93]
I pipeline'en "Hent ut lydutdrag":

- Ny lydbok i mappa: 618363180429
- Baksidetekst ikke funnet for 618363 (Fædrelandsvennen, søndag 29. april 2018)
- An error occured while handling the book

```
Traceback (most recent call last):
    File "/opt/produksjonssystem/produksjonssystem/core/pipeline.py", line 651, in _handle_book_events_thread
        self.on_book_created()
    File "/opt/produksjonssystem/produksjonssystem/make_abstracts.py", line 44, in on_book_created self.on_book()
    File "/opt/produksjonssystem/produksjonssystem/make_abstracts.py", line 130, in on_book
        mp3File_abstract = smildoc_abstract.xpath("string((//audio/@src)[1])")
UnboundLocalError: local variable 'smildoc_abstract' referenced before assignment
```

**Comment by espso** [comment]
Tror denne er fiksa, flytta smildoc_abstract i en try og printer heller traceback til loggen.
