### ISSUE TITLE
daisy_pipeline.py: process no longer exists

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#95]
Usikker på hvorfor det skjedde, men bør fanges opp og håndteres bedre.

```
Ny bok i mappa: 562285.epub

Validerer EPUB...

An error occured while handling the book

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/psutil/_pslinux.py", line 1402, in wrapper
    return fun(self, args, *kwargs)
  File "/usr/local/lib/python3.6/dist-packages/psutil/_pslinux.py", line 1506, in cmdline
    data = f.read() ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/produksjonssystem/produksjonssystem/core/pipeline.py", line 651, in _handle_book_events_thread
    self.on_book_created()
  File "/opt/produksjonssystem/produksjonssystem/incoming_nordic.py", line 47, in on_book_created
    self.on_book()
  File "/opt/produksjonssystem/produksjonssystem/incoming_nordic.py", line 67, in on_book
    dp2_job = DaisyPipelineJob(self, "nordic-epub3-validate", { "epub": epub.asFile() })
  File "/opt/produksjonssystem/produksjonssystem/core/utils/daisy_pipeline.py", line 118, in init
    if DaisyPipelineJob.start_engine(pipeline):
  File "/opt/produksjonssystem/produksjonssystem/core/utils/daisy_pipeline.py", line 98, in start_engine
    return DaisyPipelineJob.start_engine(pipeline, retries - 1)
  File "/opt/produksjonssystem/produksjonssystem/core/utils/daisy_pipeline.py", line 98, in start_engine
    return DaisyPipelineJob.start_engine(pipeline, retries - 1)
  File "/opt/produksjonssystem/produksjonssystem/core/utils/daisy_pipeline.py", line 98, in start_engine
    return DaisyPipelineJob.start_engine(pipeline, retries - 1)
  File "/opt/produksjonssystem/produksjonssystem/core/utils/daisy_pipeline.py", line 59, in start_engine
    procs = DaisyPipelineJob.list_processes()
  File "/opt/produksjonssystem/produksjonssystem/core/utils/daisy_pipeline.py", line 194, in list_processes
    cmdline = " ".join(proc.cmdline())
  File "/usr/local/lib/python3.6/dist-packages/psutil/init.py", line 665, in cmdline
    return self._proc.cmdline()
  File "/usr/local/lib/python3.6/dist-packages/psutil/_pslinux.py", line 1409, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil._exceptions.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=886, name='java')
```

**Comment by josteinaj** [comment]
Fikset i 6534e74b74905d851452b1bd1699054c55ed9f95.
