### ISSUE TITLE
Konvertering avbrytes dersom produksjonssystemet forventer å finne en mappe som ikke eksisterer

### ISSUE THREAD

**Issue by olavindergaard** [nlbdev/produksjonssystem#98]
Mulig dette kan fikses ved å kopiere en dummy-mappe:

Lagrer 558289042018 i /media/archive/distribusjonsformater/DTBook-til-talesyntese/...
558289042018 finnes i /media/archive/distribusjonsformater/DTBook-til-talesyntese/ fra før; eksisterende kopi blir slettet
An error occured while handling the book
Traceback (most recent call last): File "/opt/produksjonssystem/produksjonssystem/core/pipeline.py", line 712, in _handle_book_events_thread self.on_book_modified() File "/opt/produksjonssystem/produksjonssystem/epub_to_dtbook.py", line 36, in on_book_modified self.on_book() File "/opt/produksjonssystem/produksjonssystem/epub_to_dtbook.py", line 152, in on_book archived_path = self.utils.filesystem.storeBook(dtbook_dir, epub.identifier()) File "/opt/produksjonssystem/produksjonssystem/core/utils/filesystem.py", line 221, in storeBook self.copy(source, target) File "/opt/produksjonssystem/produksjonssystem/core/utils/filesystem.py", line 169, in copy self.copytree(source, destination) File "/opt/produksjonssystem/produksjonssystem/core/utils/filesystem.py", line 116, in copytree return shutil.copytree(src, dst, ignore=Filesystem.shutil_ignore_patterns) File "/usr/lib/python3.6/shutil.py", line 315, in copytree os.makedirs(dst) File "/usr/lib/python3.6/os.py", line 220, in makedirs mkdir(name, mode) FileNotFoundError: [Errno 2] No such file or directory: '/media/archive/distribusjonsformater/DTBook-til-talesyntese/558289042018'

**Comment by olavindergaard** [comment]
Dette er vel strengt tatt ikke en bug. Kan løses ved å kopiere inn en dummy-mappe. Jeg tenker at vi ikke prioriterer denne.
